# Generated by Django 5.2.2 on 2025-06-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='papers',
            options={'verbose_name': 'Paper', 'verbose_name_plural': 'Papers'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelOptions(
            name='requirements',
            options={'verbose_name': 'Requirement', 'verbose_name_plural': 'Requirements'},
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
        migrations.AlterModelTable(
            name='papers',
            table='paper',
        ),
        migrations.AlterModelTable(
            name='publication',
            table='publication',
        ),
        migrations.AlterModelTable(
            name='requirements',
            table='requirement',
        ),
    ]
