# Generated by Django 5.2.2 on 2025-06-09 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuit', '0002_alter_contact_options_alter_papers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papers',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='tuit.publication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
