# Generated by Django 5.2.2 on 2025-06-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuit', '0005_papers_user_publication_user_requirements_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='user',
        ),
    ]
